### ISSUE TITLE
Remove Facebook and Twitter preview

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-plugins/classicpress-seo#116]
...because things change. And there are proper tools for doing this:

https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/

and it's something else to keep updated.

**This is the FB preview in CPSEO (Social tab, page edit):**

![fb-preview](https://user-images.githubusercontent.com/4199514/91872772-289b9a80-ec70-11ea-9684-fc90d6b71a31.jpg)

**This is the FB preview using the FB tool for the same site:**

![fb-dev-preview](https://user-images.githubusercontent.com/4199514/91873396-db6bf880-ec70-11ea-9aa6-548e0b10e789.jpg)

Not an exact match.

I'm thinking we still need to be able to add an image, title and description but I'm less convinced of the usefulness of the preview.

Thoughts?

**Comment by nylen** [comment]
I would probably leave these if it's not too much trouble. They are useful assuming they can be kept updated every so often, and they don't rely directly on an external API connection so they won't break completely.

**Comment by timbocode** [comment]
Yeah, that's fair comment. If people find it useful, then it should stay in. It perhaps does need updating however.

As far as I can tell (looking through the obfuscated JS code), there is no link to FB or Tw. And also, when I load the page with dev tools open, there's no sign of any attempt to connect to 3rd party sites (other than gravatar.com and placeholder.com).

**Comment by timbocode** [comment]
FB and Twitter previews to be retained. No further action required.
