### ISSUE TITLE
Admin menu icon is too large

### ISSUE THREAD

**Issue by nylen** [ClassicPress-plugins/classicpress-seo#121]
The admin menu icon for CPSEO is a good bit larger than the icons for other menu items:

<details>
<summary>Old image - see below comment instead</summary>

![cpseo-bounding-box](https://user-images.githubusercontent.com/227022/93818151-83119080-fc49-11ea-860a-c6ac8370c76c.png)
</details>

(It's also slightly darker than the surrounding icons, but that is a bug with ClassicPress core that I will report separately)

**Comment by nylen** [comment]
Updated image with a closer match for the bounding boxes of the menu icons included with core (note that the Custom Fields / ACF icon is a little bit outside of the box also):

![cpseo-bounding-box](https://user-images.githubusercontent.com/227022/93819546-6413fe00-fc4b-11ea-9f5b-f12bebfcdcc0.png)

**Comment by joyously** [comment]
So the CSS for the menu doesn't enforce the sizes? Each plugin has to "get it right"?
This seems like a flaw in core.
