### ISSUE TITLE
please update shortcode [cpseo_contact_info]

### ISSUE THREAD

**Issue by alexlii1971** [ClassicPress-plugins/classicpress-seo#133]
Hello,

Please check this bug from orignial plugin: https://wordpress.org/support/topic/email-does-not-show-up-in-rank_math_contact_info/#post-13404488

In this case, the email address will miss. Fortuantely, they have updated and fixed it. would you please update according?

Thanks

**Comment by timbocode** [comment]
Thanks for reporting this @alexlii1971. I'll look into this shortly.

**Comment by timbocode** [comment]
This issue has been fixed in PR #134 and will be available in the next release of Classic SEO due within the next couple of weeks or so.
