### ISSUE TITLE
Classic SEO prevents saving of metaboxes position

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress-plugins/classicpress-seo#167]
These lines intentionally delete data about metaboxes, with the aim of leaving this to the plugin to manage.
But it's not working.

https://github.com/ClassicPress/classicpress-seo/blob/0cdb3f98b11b0e30769573c83399192002a9c68e/includes/admin/class-metabox.php#L364-L367

Deleting these lines makes metaboxes custom positions working again, but I'm not sure if it's the right way to fix this.

**Comment by KTS915** [comment]
Why should an SEO plugin care about the order of metaboxes on admin pages? I don't understand the purpose of that code at all.

**Comment by xxsimoxx** [comment]
If you agree I'll remove that stuff and the relative settings and open a PR.

<img width="656" alt="image" src="https://github.com/ClassicPress/classicpress-seo/assets/29772709/4e7e5187-dcdb-4768-b4f6-85fa5a623912">

**Comment by KTS915** [comment]
I don't use Classic SEO (or any other SEO plugin) so I'm just thinking out loud here. But now I see that the reason is that the plugin wants a way to push itself to the top of the plugins all the time, which has nothing to do with SEO. So I think you're safe to make that change!
