### ISSUE TITLE
Duplicate "view details" when GitHub updater is active

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress-plugins/classicpress-seo#49]
When GitHub updater is active:
![image](https://user-images.githubusercontent.com/29772709/74103093-85572c80-4b49-11ea-8edc-0146e0b67c90.png)
Switching it off:
![image](https://user-images.githubusercontent.com/29772709/74103116-b20b4400-4b49-11ea-8c9e-2e54e893ccdd.png)

## Possible workaround:
Remove [this](https://github.com/ClassicPress-plugins/classicpress-seo/blob/feabb69cdfd9c680d7b69c954858abdc4dcdf00e/classicpress-seo.php#L13) line.

**Comment by timbocode** [comment]
Thanks very much for pointing this out Simone. I do say in the announcement on the forums (https://forums.classicpress.net/t/classic-seo-beta-1-released/2115) that GitHub Updater should be removed but if you're using it for other plugins, then this isn't feasible so your workaround should be good.

I will remove that line in the next release, which probably won't be too far off.
