### ISSUE TITLE
Add usage tracking notice and opt out

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-plugins/classicpress-seo#50]
@xxsimoxx's [Stats for Update Manager](https://github.com/xxsimoxx/stats-for-update-manager) extension for Codepotent's plugin updater provides the facility to track plugin usage as shown in this example:

![cpseo-usage](https://user-images.githubusercontent.com/4199514/74128055-2e4a6980-4bd4-11ea-8cf0-b8a2a6695c5b.jpg)

Need to add a notice informing users that this is happening and **_why_**, giving them the option to opt-out if required. Similar to that introduce to Classic Commerce:

![image](https://user-images.githubusercontent.com/4199514/74127750-64d3b480-4bd3-11ea-987f-e90a732825bb.png)

**Comment by xxsimoxx** [comment]
Something about this?
![image](https://user-images.githubusercontent.com/29772709/74128997-d107e580-4bde-11ea-9f7c-de004740ade3.png)

**Comment by timbocode** [comment]
Something exactly like that 😃

**Comment by xxsimoxx** [comment]
I can do a PR quickly...

**Comment by timbocode** [comment]
...which would be great! Thanks Simone.
