### ISSUE TITLE
Sections of readme.txt are not shown in "view details"

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress-plugins/classicpress-seo#52]
`== Key Features ==` and `== Important note ==` are not shown in the *view details* tabs.

Usually this file have the same content that is put into *plugin details* in Update Manager.
But (as far as i can understand) only tabs known by CP/WP are shown:
1.  Description 
1.  Screenshots
1.  Reviews
1.  Frequently Asked Questions
1.  Installation
1.  Other Notes
1.  Changelog
1.  Upgrade Notice

**Comment by timbocode** [comment]
You should be able to see more details now Simone. It's currently got the following sections in the plugin details in Update Manager:

== Description ==
== Installation ==
== Changelog ==
== Frequently Asked Questions ==
== Other Notes ==

so you should have 5 tabs now.

**Comment by timbocode** [comment]
Closing this as it's not directly related to Classic SEO and seems to be sorted anyway.
