### ISSUE TITLE
Titles & Meta: Use custom post type's dashboard icons

### ISSUE THREAD

**Issue by elosha** [ClassicPress-plugins/classicpress-seo#62]
On the Titles & Meta page, in the sidebar: Custom post types and taxonomies that choose a dashboard menu icon (from the Dashicons font) are not shown with that icon, but a generic icon.

Example:
I have a plugin for a event post type that registers the calendar icon with
`		'menu_icon' => 'dashicons-calendar',`
but it is shown with the same pin icon like blog posts.

Also happens for custom taxonomies, both hierarchic and non-hierarchic, which are shown with the same icon like tags (non-hierarchic).

I further believe the icon von hierarchic taxonimies without chosen icon needs to be the same like category then.

**Comment by timbocode** [comment]
Thanks @elosha . Could you possibly do a screenshot of how it looks in your dashboard? And also, could you let me know which events plugin you are using. I will  then have a more detailed look into this. Thanks.

**Comment by elosha** [comment]
Here you go. Please note that "Veranstaltungen" being the event CPT.

1. Shows the issue that assigned Custom Post Type menu icons are not being honoured
2. Shows that for hierarchic Custom Taxonomies (= Category-like) the icon of non-hierarchic taxonomies (= Tag-like) is shown.

![cpseo-posttype-icons](https://user-images.githubusercontent.com/30213185/78552505-e88ed380-7807-11ea-9e50-243bb95c5767.png)

The plugin is something I wrote for a client. The relevant code is as follows:
```
[…]
/*
 * The event post type itself
 */
function elo_event_post_type() {
[…]
    // Set other options for Custom Post Type
    $args = array(
        'label'               => 'Veranstaltungen',
[…]
        'show_in_menu'        => true,
        'show_in_nav_menus'   => true,
        'show_in_admin_bar'   => true,
        'menu_position'       => 5,
	'menu_icon' => 'dashicons-calendar',
[…]
    );
     
    // Register the event post type
    register_post_type( 'event', $args );
}
add_action( 'init', 'elo_event_post_type', 0 );
[…]
```

This is the way WP Codex suggests.

**Comment by timbocode** [comment]
Sorry for the delay in getting back to you. As you can expect, things are quite difficult at the moment.

Regarding icons for custom post types, there are a couple of filters you can add to `functions.php` as in these examples:

```
add_filter( 'cpseo/taxonomy_icons', function( $icons ) {
	$icons['event_cat'] = 'dashicons dashicons-category';
	return $icons;
});
```

```
add_filter( 'cpseo/post_type_icons', function( $icons ) {
	$icons['event'] = 'dashicons dashicons-calendar';
	return $icons;
});
```
Replace `event` and `event_cat` with your own types.

Does this help at all?

**Comment by elosha** [comment]
No worries, it's a busy time here, too. And it's just a aesthetic issue …

Thanks for the hint. It helps to enhance my plugin to improve CPSEO compability and I appreciate your help very much. :)

I just wondered if CPSEO couldn't query the icon from the post type options structure right away, like it already queries the post type name/label. This would solve the problem globally and elegantly. But it might be that it's not that trivial ;)

Otherwise I accept your solution. :)

**Comment by timbocode** [comment]
Yes, sorry. I should have mentioned that the filters are just meant as a workaround until I can create a proper solution. It is possible to query the icon from the post type and that's what I aim to do, hopefully in the next (beta 4) release.

Thanks for the feedback :)

**Comment by timbocode** [comment]
I'll keep this open for the time being. I'm working on a proper fix now, ready for beta 4.
