### ISSUE TITLE
Possible privilege escalation

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress-plugins/classicpress-seo#66]
Posted in Slack. Reposting here as CSEO is based on Rank Math.

https://www.wordfence.com/blog/2020/03/critical-vulnerabilities-affecting-over-200000-sites-patched-in-rank-math-seo-plugin/

**Comment by xxsimoxx** [comment]
I had a quick look but vulnerable code seems not to be in CPSEO.

**Comment by johnalarcon** [comment]
Cool. Not sure why someone would post it in Slack and not here.

**Comment by timbocode** [comment]
I was looking into it earlier and can confirm that the vulnerable code does not exist in Classic SEO. 

The code in question seems to have been introduced in RM 1.0.36 and is related to the addition of support for Gutenberg. 

Classic SEO doesn't contain any code from RM 1.0.36 onwards but thanks for reporting it.
