### ISSUE TITLE
Rename plugin

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-plugins/classicpress-seo#8]
After a forum discussion culminating in this post [https://forums.classicpress.net/t/plugin-theme-naming-conventions-when-to-use-classicpress-and-or-cp/1653/8](https://forums.classicpress.net/t/plugin-theme-naming-conventions-when-to-use-classicpress-and-or-cp/1653/8) it was agreed to rename the plugin `Classic SEO`. 

This is pending the release of formal guidelines which are expected to state that the use of the word '**classicpress**' in plugin and theme names is to be avoided.

This is a major update requiring changes to the code and database. 

For v0.3.0. An updater function will be included to update existing installations.

**Comment by timbocode** [comment]
The plugin was renamed Classic SEO in v0.3.0 but the directory name is still `classicpress-seo` and the main PHP file is still `classicpress-seo.php`. These two issues to be addressed in forthcoming release.

**Comment by xxsimoxx** [comment]
I've faced this problem some time ago.
Since (or i haven't find something better) it involves some user action (reactivating plugin after update or ask the user to do something) my suggestion is to do this in the *same release* where you are going to switch from GitHub updater to Update Manager because GitHub updater don't seems to like these changes... then you can change the name of the repo without any other problem.
Just my 2 cents...

**Comment by timbocode** [comment]
Thanks @xxsimoxx. I've not given this much thought lately but it is a bit of a tricky one. I've been trying to find ways of doing it all automatically but I'm not sure it's worth all that effort.

I am actively working on integrating Update Manager into Classic SEO right now so your timing is perfect and what you say makes good sense.

James has suggested leaving it as classicpress-seo , partly because it's easier and partly because he thinks it's something we can live with and I tend to agree with him. I've not fully decided yet but from what you're saying, I need to make that decision now.

Thanks for your input Simone. Appreciated.

**Comment by timbocode** [comment]
Closing this as won't fix, particularly as it's now an "official" CP plugin.
